kumuluzee:
  name: user-management-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
  - jndi-name: jdbc/UserDS
    connection-url: jdbc:postgresql://192.168.99.100:5432/user #TODO check this
    username: dbuser
    password: postgres
    max-pool-size: 20
  health:
    checks:
      data-source-health-check:
        jndi-name: jdbc/UserDS
  config:
    etcd:
      hosts: http://192.168.99.100:2379
  discovery:
    etcd:
      hosts: http://192.168.99.100:2379
  metrics:
    web-instrumentation:
    - name: users-endpoint
      url-pattern: /v1/users/*
app-properties:
  external-services:
    enabled: false
  healthy: true