kumuluzee:
  name: user-management-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  datasources:
  - jndi-name: jdbc/OrdersDS
    connection-url: jdbc:postgresql:/localhost/192.168.99.100:5433/user #TODO check this
    username: dbuser
    password: postgres
    max-pool-size: 20